remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
name: ROM Robotics & Deep Blue AI Lab
title: Open Source AI & Robotics For Myanmar
description: ROM Robotics, Research & Developments in Automation, was established in 07 July 2017.
